version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]
  dialect = "typescript"
  module_system = "es-modules"

[[analyzers]]
name = "secrets"
enabled = true
